name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSHPRIVATE }}

      - name: Deploy on Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.IP_VM }} << 'EOF'
          cd /home/${{ secrets.USER_NAME }}/DevPrueba/
          git pull origin main
          sudo docker-compose down --remove-orphans
          sudo docker-compose pull
          sudo docker-compose build --no-cache
          sudo docker-compose up -d --force-recreate --remove-orphans
          EOF
        env:
          SSH_PRIVATE_KEY: ${{  secrets.SSHPRIVATE }}
        shell: bash
